# Generated by Django 4.2.1 on 2023-06-04 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0003_remove_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='activation_code',
            field=models.IntegerField(blank=True, null=True, verbose_name='код'),
        ),
    ]
