# Generated by Django 4.2.1 on 2023-06-05 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0005_remove_user_activation_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='activation_code',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='код'),
        ),
    ]
