# Generated by Django 4.2.1 on 2023-06-05 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0008_user_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='image',
        ),
    ]
