# Generated by Django 4.2.1 on 2023-06-16 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0010_alter_user_options_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='image/'),
        ),
    ]
