# Generated by Django 4.2.1 on 2023-06-16 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0011_alter_user_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='image',
        ),
    ]
