# Generated by Django 4.2.1 on 2023-06-17 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0014_remove_user_image_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='images/default.jpg', null=True, upload_to='avatar/'),
        ),
    ]
