# Generated by Django 4.2.1 on 2023-06-17 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0017_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='avatar/default.jpg', null=True, upload_to='avatar/'),
        ),
    ]
