# Generated by Django 4.2.1 on 2023-06-22 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0019_alter_user_options_rename_first_name_user_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
