# Generated by Django 4.2.1 on 2023-06-22 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0022_remove_user_activation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
