# Generated by Django 4.2.1 on 2023-07-04 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0026_alter_user_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='first_name',
        ),
    ]
