# Generated by Django 4.2.1 on 2023-07-04 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0027_rename_username_user_first_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='first_name',
            new_name='username',
        ),
    ]
