# Generated by Django 4.2.1 on 2023-05-24 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_post_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.FileField(upload_to='audio_comments'),
        ),
    ]
