# Generated by Django 4.2.1 on 2023-06-03 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_post_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-created_at',)},
        ),
    ]
